author: 4dU8DsWKlLDjAN7cAdXxkQ
category: New Eden News
content:
- body: "![](http://www.eve-mercury.net/images/mercurybanner.png)  \n  \nPashanai
    - The Scope is still attempting to get news on the explosion that apparently ripped
    through the Ministry of War's Bureau Offices in the Pashanai system. Reports are
    coming in, but the explosion's cause and the extent of damage remain unclear.\n\nWhat
    is clear is that the Amarr Navy has begun a massive re-deployment along its border
    with the Minmatar Republic. We have no comment from the Navy at this time."
  id: 6n8XcrbErlYhjsgmHxMPuK
  layout: default
description: Pashanai - The Scope is still attempting to get news on the explosion
  that apparently ripped through the Ministry of War's Bureau Offices in the Pashanai
  system. Reports are coming in, but the explosion's cause and the extent of damage
  remain unclear. What is clear is that the Amarr Navy has begun a massive re-deployment
  along its border with the Minmatar Republic. We have no comment from the Navy at
  this time.
heroImage: null
id: 6TwoqO3yYAilE4MYlB2W0J
image: null
listingImage: null
parent: null
publicationDate: '2010-03-25T00:00:00'
slug: breaking-explosion-cause-unclear-amarr-navy-redeployment
sortOrder: 0
title: 'BREAKING: Explosion cause unclear, Amarr Navy redeployment'
topics: []
updatedAt: '2021-06-11T20:34:57.300000+00:00'
