author: 4dU8DsWKlLDjAN7cAdXxkQ
category: New Eden News
content:
- body: 'Renyn, Essence - In a press conference at the headquarters of the Federal
    Intelligence Office today, a senior spokesman announced the conclusion of several
    months of investigation into shipping giant Federal Freight. The inquiries, conducted
    by the Special Department of Internal Investigations, were aimed at establishing
    direct involvement in the loss of sensitive data by Federal Freight employees,
    in addition to ascertaining any possible connections to Caldari intelligence organizations.


    Much to the relief of its management and major shareholders, Federal Freight was
    cleared of any and all espionage charges. The investigation did point out a number
    of significant gaps in the firm''s data security practices, however, leading to
    the resignation of facilities security manager Hayden LeDour. As penalty for putting
    national security interests at risk, Federal Freight has been barred from bidding,
    performing, or subcontracting any Federation Navy contracts for the next eighteen
    months. In addition, Federal Freight has agreed to increased security auditing
    by the FIO to prevent any future compromises of sensitive information.


    Federal Freight''s stock tumbled another twenty percent on the news before stabilizing
    at a four-year low.'
  id: 2Mq3oRn52teltD8dbXmxaT
  layout: default
description: Renyn, Essence - In a press conference at the headquarters of the Federal
  Intelligence Office today, a senior spokesman announced the conclusion of several
  months of investigation into shipping giant Federal Freight. The inquiries, conducted
  by the Special Department of Internal Investigations, were aimed at establishing
  direct involvement in the loss of sensitive data by Federal Freight employees, in
  addition to ascertaining any possible connections to Caldari intelligence organizations.
  Much to the [...]
heroImage: null
id: 2lUuDDsmpsXg2IqhkLpbZN
image: null
listingImage: null
parent: null
publicationDate: '2008-12-24T10:38:57'
slug: federal-freight-cleared-of-espionage-charges-penalized-for-lax-security
sortOrder: 0
title: Federal Freight Cleared of Espionage Charges, Penalized for Lax Security
topics: []
updatedAt: '2021-06-11T20:26:13.956000+00:00'
