author: 4dU8DsWKlLDjAN7cAdXxkQ
category: New Eden News
content:
- body: "![](http://www.eve-mercury.net/images/mercurybanner.png)  \n  \nAmarr Prime
    - Renowned composer Khitian Maritak, whose numerous canticles earned her the coveted
    Theology Council title \"The Holy Inspired\" and whose recent historical opera,
    \"The Trials of Jiustan and Daro,\" won acclaim across the cluster, has announced
    the her latest creation, a choral titled \"Sarum Symphony.\"\n\nJamyl Sarum's
    mysterious and explosive return to power two years ago signalled the beginning
    of a new era for the Amarr Empire. This symphonic piece is to be performed in
    the Grand Nave of the Basilica of Saint Nhyron on Mekhios by the imperial choir
    Voices of the Sefrim, and will be directed by Maritak herself. The composer created
    the choral over the course of seven exhaustive months to commemorate the event.
    The Khanid-born Maritak has declared the piece to be her \"magnum opus.\"\n\nCriticism
    has been levelled for the composer's choice of venue: Saint Nhyron was a notoriously
    outspoken opponent of the Sarum family during the last Ardishapur reign, though
    no ill will has existed between the houses in recent centuries. Maritak insists
    that her selection of the building is purely artistic, that the \"Sarum Symphony\"
    was written specifically for performance in the basilica in order to utilize the
    chuch's striking acoustic properties, and that the contentious history has no
    bearing on the choice.\n\nThe symphony's debut performance will be held on Lightbringer's
    Eve, a planetary holiday celebrating the first day of springtime. Invitation to
    the event is limited to members of the Theology Council, the Privy Council, heirs,
    and the Empress herself. A live broadcast will be held across the Empire by the
    ACN for the benefit of all Amarr citizens. Security for the event is expected
    to be tight in light of the recent attack by the Bloody Hands of Matar and the
    ongoing Sansha threat."
  id: 3YvUoFUrJqFUfcOHEy1pWf
  layout: default
description: Amarr Prime - Renowned composer Khitian Maritak, whose numerous canticles
  earned her the coveted Theology Council title "The Holy Inspired" and whose recent
  historical opera, "The Trials of Jiustan and Daro," won acclaim across the cluster,
  has announced the her latest creation, a choral titled "Sarum Symphony." Jamyl Sarum's
  mysterious and explosive return to power two years ago signalled the beginning of
  a new era for the Amarr Empire. This symphonic piece is to be performed in the Grand
  Nave of the [...]
heroImage: null
id: 45yP3HfgM5tifEZA1DE2fo
image: null
listingImage: null
parent: null
publicationDate: '2010-06-29T13:48:34'
slug: honored-composer-to-commemorate-empress
sortOrder: 0
title: Honored Composer to Commemorate Empress
topics: []
updatedAt: '2021-06-11T20:14:18.383000+00:00'
