author: Lina Ambre
category: New Eden News
content:
- body: "Caille, Gallente Prime - President Celes Aguard has formally assumed leadership
    of the Gallente Federation following her inauguration today in Caille, the traditional
    capital of the Federation Union of Gallente Prime. Under heavy security, outgoing
    President Jacus Roden administered the oath of office to President Aguard on the
    Dais of the Four Freedoms in Liberty Square, Central Caille.\n\nDespite the unusually
    high security measures, a consequence of the February Election Attacks, large
    crowds thronged Liberty Square, Crystal Boulevard and many streets of Central
    Caille. With so many from the diverse communities of Caille on the streets, and
    with many interstellar visitors, a carnival atmosphere was achieved, despite the
    ubiquity of Caille Gendarmes and Federal Police.\n\nAfter administering the Presidential
    Oath to Celes Aguard, Jacus Roden made a short valedictory address in which he
    pledged to \"continue to serve the peoples of the Gallente Federation in any and
    every way that I can.\" Jacus Roden's plans for private life are not known and
    he has made himself available to the Aguard administration's transition team in
    the short term.\n\n![](https://web.ccpgamescdn.com/fiction/eveonline/worldnews/images/President_Celes_Aguard.jpg)
    \ \n_Above: President Celes Aguard_\n\nMaking her inaugural address, President
    Celes Aguard thanked Jacus Roden for his presidential service and for \"resolutely
    and loyally ensuring a peaceful transfer of power in the democratic tradition
    of our great Federation, despite grave and vicious attacks on our way of life.\"\n\n\"Our
    Federation is a shining beacon of liberty in this universe, providing a realm
    for all the people to pursue their prosperity, with all their vital diversity,
    and in unity with their fellow citizens. As it has been, so it shall be under
    my administration and this Gallente Federation will be for all the peoples who
    live within it, no matter where they live. Whether it be Luminaire or Reblier,
    Crux or Beyt, Essence or Solitude, all the territories of the Federation will
    receive the support and security they are due under my administration.\n\n\"Nor
    shall my administration seek to impose a central vision on the many and varied
    cultures of our diverse and far-flung Federation. The principles of autonomous
    democracy, local sovereignty and co-operative federation will be upheld and strengthened
    by my federal administration. Equally, the unity and prosperity of our great Federation
    is threatened by interstellar war and internal threats alike. My administration
    places the highest importance on achieving peaceful co-existence with our neighbors,
    and total and implacable resistance to those who would destroy our way of life,
    whether that be by invasion, terrorism or subversion.\n\n\"My fellow citizens
    of the Federation Union, you have placed the highest trust in me and I am deeply
    humbled by it. I shall serve you and the principles of our great Gallente Federation
    until my dying breath. Peace, prosperity and liberty to all!\"\n\nRepresentatives
    of the other major empires were present at the inauguration and are understood
    to have had meetings with President Aguard. From the Caldari State, Hyasyoda CEO
    Ahtonen Osmon, Lai Dai CEO Alakoni Ishanoya, and Sukuuvestaa CEO Kuikiainen Onita
    represented the Chief Executive Panel.\n\nLeading the Minmatar Republic delegation,
    Sanmatar Maleatu Shakor chose to personally attend, underlining the importance
    the Tribal Council places on close relations with the Gallente Federation. Chiefs
    Acassa Midular and Einnar Aeboul, of the Sebiestor and Thukker Tribes respectively,
    were also present.\n\nFor the Amarr Empire, Lady Ersilia Kor-Azor and Lord Tunir
    Tash-Murkon headed a delegation keen to establish improved diplomatic and trading
    relations with the new Gallente administration. Lord Governor Ekroz Salaf of the
    Ammatar Mandate was also in attendance, while the Khanid Kingdom was represented
    solely by its ambassador to the Federation.\n\n**In Other News**\n\n  * Many New
    Senators Enter Gallente Federal Senate as \"Anti-Centralist, Hawkish and Ethnic
    Groups Make Gains\" - _Villore Guardian_\n\n\n  * Intaki Assembly Expresses \"Deep
    Concern\" at Caldari State Protectorate Resumption of Control in Intaki System\n\n\n
    \ * Minmatar Tribal Council Authorizes Republic Security Services to \"Eliminate
    Angel Cartel Presence and Restore Order on Skarkon II\"\n\n\n  * Tronhadar Free
    Guard Seizes Control of Mahonisgard on Skarkon II Following Agreement Between
    Eifyr & Co. and CBD Corporation\n\n\n  * Reports from Skarkon II of Onikanabo
    Brigade Mercenaries Landing in CBD Corporate Zone; \"No Comment\" \\- CBD Corporation\n\n\n
    \ * Shipping Agents Report Large Movements of Krusual and Thukker Mercenary Corporations
    Through Hek - _Metropolis Financial Journal_\n\n\n  * Expert Distribution Signs
    Contract with Minmatar Territorial Defense Guards to \"Supply Small Arms, Ammunition
    and Accessories\"\n\n\n  * Hyasyoda Corporation Files \"Record First Quarter Sales
    of Military Aerospace Products\"; Expects to File \"Strong Second Quarter Performance\"\n\n\n
    \ * Lai Dai and Quafe Dismiss Reports that Thefts of Subcranial Nanocontroller
    Shipments Jeopardize PKN Interstellar's Consumer Tech Roadmap\n\n\n  * Empress
    Catiz I Issues Summons to Royal Heirs for Privy Council Meeting on Interstellar
    Diplomacy and Trade Next Week\n\n\n  * Lord Aslan Ul-Qosh of Oris Orders New Investigation
    of \"Terrorist Attacks on Planetary Holdings\"; Insists on Purge of Local MIO"
  id: qPfQYZoTO3tfiUdPHWhCv
  layout: default
description: Caille, Gallente Prime - President Celes Aguard has formally assumed
  leadership of the Gallente Federation following her inauguration today in Caille,
  the traditional capital of the Federation Union of Gallente Prime. Under heavy security,
  outgoing President Jacus Roden administered the oath of office to President Aguard
  on the Dais of the Four Freedoms in Liberty Square, Central Caille. Despite the
  unusually high security measures, a consequence of the February Election Attacks,
  large crowds thronged [...]
heroImage: null
id: 4Ik0yHzUlqE8oFXQRICTaI
image: null
listingImage: null
parent: null
publicationDate: '2020-05-15T18:46:00'
slug: inauguration-of-gallente-president-celes-aguard-held-under-heavy-security
sortOrder: 0
title: Inauguration of Gallente President Celes Aguard Held Under Heavy Security
topics: []
updatedAt: '2021-06-11T20:16:39.569000+00:00'
