author: Ret Gloriaxx
category: New Eden News
content:
- body: "Yulai, Genesis - An active information worm attributed to the Triglavian
    Collective has been deployed to the GalNet fluid router system, reports the Secure
    Commerce Commission. The purpose of the worm appears to be to interact with Triglavian
    filament technology, reconfiguring it to permit support of frigate-sized ships.\n\nThe
    self-replicating and -propagating information worm has spread itself across the
    fluid router network at \"extraordinary speed\" according to sources in the SCC.
    \"We're unable to stop it and it's distributed itself across thousands of light-years
    of router connections. I don't think there's ever been a worm with that long a
    tail,\" said one information warfare officer.\n\nWhile the worm has spread rapidly
    and widely, information security specialists have been analyzing examples of its
    cellular code and payload in secured, unentangled and air-gapped \"black box\"
    computing environments. SCC analysts believe it poses little to no threat to normal
    operations of the GalNet system, SCC market network, or other computer and information
    networks.\n\n![](https://webimg.ccpgamescdn.com/7lhcm73ukv5p/5XTnhfQDPU6Ace4AIAMk8K/5c255797d0b387e1632c528516d891e4/2_1920x1124.jpg_w=900&fm=jpg&fl=progressive)
    \ \n_Triglavian_ Damavik _-class ships in Abyssal Deadspace_\n\nThe purpose of
    the Triglavian Collective in apparently unlocking the capability for small groups
    of frigates to enter Abyssal Deadspace remains obscure. The Collective continues
    to fight a war with the Drifters in its domains, by all accounts, and some have
    speculated that it seeks allies in this struggle. Others theorize that Triglavian
    culture involves extensive use of ritual, including forms of gladiatorial combat
    that serve an important purpose in a posited  \"dominance hierarchy\".\n\nAnother
    theory is that the Triglavians are deliberately luring ships from New Eden into
    the Abyssal realm so as to sample our technology, gain intelligence or even harvest
    biomass. Whatever the case may be, Abyssal Deadspace is opening to groups of up
    to three frigates and collaborative exploration of the depths of this mysterious
    realm will be possible.\n\n_____\n\n_(For more information about developments
    in Abyssal Deadspace see the[Abyssal Onslaught devblog](https://www.eveonline.com/article/phtxmk/abyssal-onslaught-new-content-coming-to-the-abyss).)_"
  id: 3VHGbEoVPuZtTiOFlV5pvZ
  layout: default
description: Yulai, Genesis - An active information worm attributed to the Triglavian
  Collective has been deployed to the GalNet fluid router system, reports the Secure
  Commerce Commission. The purpose of the worm appears to be to interact with Triglavian
  filament technology, reconfiguring it to permit support of frigate-sized ships.
  The self-replicating and -propagating information worm has spread itself across
  the fluid router network at "extraordinary speed" according to sources in the SCC.
  "We're unable to [...]
heroImage: null
id: misActtp2CkyoL1oBmk8Y
image: null
listingImage: null
parent: null
publicationDate: '2018-11-13T11:01:24'
slug: mysterious-triglavian-galnet-worm-unlocks-abyssal-filament-configuration-for-frigates
sortOrder: 0
title: Mysterious Triglavian GalNet Worm Unlocks Abyssal Filament Configuration for
  Frigates
topics: []
updatedAt: '2021-06-11T20:15:14.146000+00:00'
