author: 4dU8DsWKlLDjAN7cAdXxkQ
category: New Eden News
content:
- body: "JITA \u2013 THE FORGE. After what was a week of low-keyed grumbling about
    \u201Cincreased commodity prices\u201D and \u201Clogistic nightmares\u201D from
    the pod pilot community, the bustling Niyabainen \u2013 Jita \u2013 Sobaseki hub
    at the heart of the Caldari state seems busier than ever.   \n  \n\u201CCan\u2019t
    help but expect that next time the CEP decides such a major logistic revamping
    we get informed in advance\u201D, said Oikanen Hilo, ship manufacturer at Kisogo
    \u201Cyet it does seem some of the changes may have a positive impact on business.
    Although commodities have gone slightly up this week, it has been clearly offset
    by the increase of traffic on the Niya \u2013 Soba route and systems nearby.\u201D
    \  \n  \nModule trader Hurozi Aikken from Isaziwa had no unclear position on the
    matter: \u201CYulai was killing us. Cheap imports from Minmatar space were sweeping
    our profit margins under the sewer. I\u2019m all for free markets and competition,
    but products sold below mineral prices and with technology \u201Cborrowed\u201D
    from other Empires is clearly not what free markets are about. Something had to
    be done, and it was done indeed. Although we are no match to the Jita corridor,
    we expect an increase of traffic here at The Citadel too.\u201D   \n  \nTo whether
    or not this may hurt Caldari exports, Mr. Aikken was also positive: \u201COn the
    contrary, the Caldari State should benefit the most. We are unrivalled in high-tech
    products, which are the least affected by freight cost due to their low volume
    and high value. And when it comes to commodities\u2026 you only have to see which
    Freighter has the biggest capacity to notice that this move was anything but sloppy\u201D.
    \  \n  \nWill Jita be the new Yulai? \u201CTime will tell\u201D, said Mohitie
    Amon, Advanced Trade professor at STI in Dantumi, \u201Cyet one thing is clear:
    regardless of other reasons, each Empire is trying to protect their internal markets.
    Military might means little if you do not have the economic power to back it up.
    \  \n  \nAny Economy student knows that the ideal of a healthy economy is to focus
    on products with high added value, while at the same having access to cheap raw
    materials. With the new routes and by licensing Freighter technology to freelance
    pod-pilots, each Empire will assure that the flow of industrial commodities into
    their hubs will not be interrupted, while at the same time encouraging the consumer
    to prefer locally produced finished goods.   \n  \nIn this new scenario, it is
    highly unlikely that any one system will hoarde most of the traffic and regions
    will compete with different products. Pator has an interesting chance of attracting
    pod-pilots interested in cheap, low-tech solutions to their ship\u2019s configuration,
    and there is no doubt that Oursulaert will attract those interested in good taste
    and style, as it always has. Yet when it comes to innovative, bleeding edge technologies
    I would put my Isk and my shop not far from Jita.\u201D"
  id: 7d9cXwdWnoRgKZZkNoPEHs
  layout: default
description: "JITA \u2013 THE FORGE. After what was a week of low-keyed grumbling
  about \u201Cincreased commodity prices\u201D and \u201Clogistic nightmares\u201D
  from the pod pilot community, the bustling Niyabainen \u2013 Jita \u2013 Sobaseki
  hub at the heart of the Caldari state seems busier than ever. \u201CCan\u2019t help
  but expect that next time the CEP decides such a major logistic revamping we get
  informed in advance\u201D, said Oikanen Hilo, ship manufacturer at Kisogo \u201Cyet
  it does seem some of the changes may have a positive impact on business. Although
  [...]"
heroImage: null
id: 3PhFUKNz0uei4HpIbZh4p3
image: null
listingImage: null
parent: null
publicationDate: '2005-07-11T23:55:43'
slug: new-routes
sortOrder: 0
title: New routes
topics: []
updatedAt: '2021-06-11T20:41:57.886000+00:00'
