author: 4dU8DsWKlLDjAN7cAdXxkQ
category: New Eden News
content:
- body: "SIRPPALA - Executives of Kaalakiota Corporation held an emergency meeting
    at the company HQ in Nonni in response to developing industrial action taken by
    workers in Sirppala and Waskisen following an insurgent attack on Sirppala II.
    \n\nA group of masked individuals launched a guerrilla attack on a guard post
    at the Kaalakiota Factory on the planet, injuring two security employees and defacing
    the building. \n\nUnion leaders have been increasingly disgruntled in recent months
    as industrial relation talks between the two sides ended in stalemate, with the
    major sticking points being an improvement in the working conditions coupled with
    a pay freeze in the face of threats of cuts to wages. However, the escalation
    to the point of violence by the insurgents has added a new twist to developments.
    \n\nNiteloho Koirolen, Chief Co-Ordinator of Public Relations at Kaalakiota Corporation
    said: \"We have lost as much as 85% of man hours with this illegal action. The
    brave workers that attempted to perform their duties have been attacked. \n\nHe
    added: \"The economic situation in these systems is terrible; we have lost about
    90% of production and are losing billions a day. The irony is that if it continues,
    the pay-cuts the union fought so long to avoid will become necessary. \n\nKoirolen
    issued a warning to the insurgents, saying: \"We will not rest until we find those
    responsible for what happened on Sirppala II and when we do find them they better
    hope other authorities get there first. Our internal security division is currently
    drawing up plans to restore order in the systems involved with the minimum of
    disruption to daily activities.\" \n\nKaalakiota CEO Haatakan Oiritsuu cut short
    an award ceremony in Goram to return to Nonni when news of the severity of the
    dispute reached her. \n\nAt the picket lines, foreman Kajikkila Uotiri remained
    defiant. He explained: \"We only want to be able to do our jobs safely and get
    paid what we deserve. If Kaalakiota can't understand that then there's no hope
    for them.\" \n\nThe strikes have spread to Waskisen and rumours have already started
    as to whom the insurgents belonged to given that the attack appeared far more
    professional than just disgruntled workers. Many fingers are being pointed in
    the direction of Sukuuvestaa Corporation, who stands to gain the most from the
    current situation."
  id: 3X385QvQ9yCdpa0a6TTuXH
  layout: default
description: SIRPPALA - Executives of Kaalakiota Corporation held an emergency meeting
  at the company HQ in Nonni in response to developing industrial action taken by
  workers in Sirppala and Waskisen following an insurgent attack on Sirppala II. A
  group of masked individuals launched a guerrilla attack on a guard post at the Kaalakiota
  Factory on the planet, injuring two security employees and defacing the building.
  Union leaders have been increasingly disgruntled in recent months as industrial
  relation talks [...]
heroImage: null
id: 4X9Zet4yhCA5nsT3IzfDuL
image: null
listingImage: null
parent: null
publicationDate: '2006-12-09T05:43:13'
slug: terrorists-strike-kaalakiota-security
sortOrder: 0
title: Terrorists strike Kaalakiota security
topics: []
updatedAt: '2021-06-11T20:30:56.758000+00:00'
