author: null
category: New Eden News
content:
- body: "![Gulmorogod](//images.ctfassets.net/1gqwxa4vbed9/4bahw6cx79f5BHIFPikKPd/71909b83772c72f961dd35de56bda824/image.png)\n<div
    align=center style=\"font-style:italic;margin:-1.75em 0em 2em\">Above: Sunrise
    over Gulmorogod IV, recent target of Vanguard Insurgency deployments.</div>\n\n###
    Planetary Defense Hacks Halt as Vanguard Retreat\n\nGulmorogod IV \u2013 Ground
    sources on the prior host planet of an Angel insurgency FOB confirmed a halting
    of Deathless planetary defense network disruptions yesterday. This coincided with
    a reported drawing-back of \u201CVanguard\u201D warclone deployments from the
    planet, concluding a two week period of action that began in the Raihbaka system.
    \n\nIn this location as well as the previous Guristas insurgency in Raihbaka,
    Vanguard were widely reported engaging in combat on both sides of conflicts in
    significant numbers, with higher rates of pirate support overall. Vanguard activity
    ultimately enabled a Guristas victory in Raihbaka, and contributed greatly to
    Cartel operations in Gulmorogod. Notably, despite a consistent disadvantage in
    raw numbers, Legion-aligned Vanguard claimed the majority of skirmish victories
    on seven of fourteen days of activity. Many have attributed this spread of loyalties
    to the core Vanguard population's primary origin as \u201Cfirst-generation\u201D
    warclones who sought refuge offered by the Angels, Guristas, and Legion beginning
    in [early YC115.](https://universe.eveonline.com/new-eden-news/mordus-legion-and-angel-cartel-join-guristas-in-offering-to-aid-caldari-targets)
    \n\nWith Vanguard deployments no longer occupying planetary defense infrastructure
    sites, pirate activity previously attracted to these remote areas has returned
    to previous targets. Local reactions have been varied, with much discussion centering
    on the Deathless Wraiths' apparent decision to not directly provide the means
    to hack planetary defense infrastructure to pirate forces.\n\n\u201COn one hand,
    these defense hacks and Vanguard skirmishes pulled the majority of conflict far
    away from civilian districts,\u201D stated local news personality Hesmira Rattosk
    of affiliate program *Gulmorogod WorldWide*. \u201COn the other, this means we\u2019re
    dealing with an organization well beyond Empire or CONCORD authority happily insinuating
    itself as a third party in pirate activity that only became possible in the first
    place because of infrastructure *they provided.*\"\n\nRattosk concluded: \u201CFirst
    the Circle markets shipcaster and FOB access to pirates, making them dependent.
    Next they show off an unprecedented ability to hack planetary defenses, keep it
    to themselves, and jump in as middlemen for these next-gen warclones offering
    their services on either side, leaving both insurgents and the Legion with no
    choice but to employ them. Bald-faced war profiteering aside, if this \u2018Deathless\u2019
    and his allies are trying to make their tech and services a necessity, they\u2019re
    damn well succeeding.\u201D\n\n### Vanguard Freelance Trials Produce Mixed Outcomes\n\nIn
    the far reaches of nullsec, Vanguard freelance trials conducted by the Agency
    network\u2019s controlling mercenary organizations yielded significant yet highly
    varied results on planets threatened by emerging resistance to Equinox workforce
    colonies.\n\nVanguard activity on DHR-H7 VII (Branch) and JZV-F4 II (Vale of the
    Silent) strongly favored Guristas and Deathless operations respectively. Contracts
    from Guristas agent Ohminen Sin supporting raids on local colony assets proved
    exceptionally popular, with completions totaling over twice the number reported
    for all but one other offering. This sole exception was on JZV-F4 II, where tasks
    dispensed on behalf of the Deathless Circle by \u201CThe Peacock\u201D resulted
    in the stonewalling of Society of Conscious Thought acquisition efforts.\n\nConcurrently,
    Equinox colonies on H74-B0 II (Querious) and 4-EFLU II (Wicked Creek) reported
    overwhelming support from freelancers. Asset denial operations under Mordu\u2019s
    Legion Strike Commander Tsuni Aina sustained the highest completion ratio of all
    recorded contracts, significantly hampering Salvation Angel activity. Assistance
    rendered on H74-B0 II likewise enabled colony personnel to resist Blood Raider
    strikes targeting Upwell cloning materials, counteracting overall higher support
    for these pirates versus the opposing forces of the Order of Saint Tetrimon.\n\nMeanwhile,
    in the background of respective Angel and Guristas operations, new retrievals
    of cloning and colony tech for Circle associates \u201CLifegiver\u201D and \u201CThe
    Quartermaster\u201D hint at new R&D and refinements yet-to-come in the evolution
    of the Vanguard. Whatever the future may hold for this new generation, the results
    of recent deployments speak for themselves.\n\nThe Scope will report on further
    developments as they emerge.\n\n### News in Brief\n\n- Legion founder Muryia Mordu
    dismisses criticism of recent Vanguard employment.\n\n- Wormhole-stationed SoE
    operatives note shift in Drifter-controlled Sleeper drone activity.\n\n- Widespread
    hangar noise complaints as capsuleers repeatedly test new boarding protocol.\n\n-
    Capsuleers sight Hrada-Oki bivouacs offering trades for Atavum, Encrypted Infomorphs.\n\n-
    New \u201CInspector BOB\u201D drones receive warm reception in station hangars
    across New Eden.\n\n- EDENCOM scouts report rising threat level around Pochven
    Dazh Liminality Loci.\n\n- Sansha's Nation and ORE mobilizations continue in Volatile
    Ice Storms."
  id: 1F306YaNTZRExj6aqhLMYZ
  layout: default
description: "Above: Sunrise over Gulmorogod IV, recent target of Vanguard Insurgency
  deployments. Planetary Defense Hacks Halt as Vanguard Retreat Gulmorogod IV \u2013
  Ground sources on the prior host planet of an Angel insurgency FOB confirmed a halting
  of Deathless planetary defense network disruptions yesterday. This coincided with
  a reported drawing-back of \u201CVanguard\u201D warclone deployments from the planet,
  concluding a two week period of action that began in the Raihbaka system. In this
  location as well as the [...]"
heroImage: null
id: 6jTNG9o4DMxrWAW3wyyc2n
image: null
listingImage: null
parent: null
publicationDate: '2024-12-14T00:00:00'
slug: vanguard-deployments-recede-after-two-weeks-of-intense-activity
sortOrder: null
title: Vanguard Deployments Recede After Two Weeks of Intense Activity
topics:
- Warclones
updatedAt: '2024-12-14T09:01:37.341000+00:00'
