author: 4dU8DsWKlLDjAN7cAdXxkQ
category: Interstellar Correspondents
content:
- body: "![](http://www.eve-ic.net/media/assets/icarticlebanner.png)  \n  \n **New
    Caldari, The Forge** \u2013 Sansha\u2019s Nation forces have been assaulting trade
    routes throughout New Eden, disrupting both market hubs hubs and popular shipping
    routes.   \n  \nOver the past two weeks, Sansha\u2019s Nation forces have attacked
    multiple solar systems including Kador Prime, New Caldari and Altrinur. It is
    their newfound interest in trade routes, however, that is causing concern among
    capsuleers.   \n  \nCapsuleer Ace Echo, who was present during the New Caldari
    attack, said \u201CThis recent rash of attacks seems to be part of Kuvakei's plan
    to disrupt and destroy capsuleer resistance directly. Attacking the economic base
    of the galaxy is a sure way to grab attention and to do damage to the core of
    New Eden.\u201D He went on to speak specifically about the New Caldari incursion.
    \u201CThis assault, close to a gate into Jita, was successful in taking out many
    neutral trading ships that were unsuspecting of the dangers at the gate.\u201D
    He believed that a Nation attack in Jita itself would prove too difficult for
    a Nation force, however, drawing swift and powerful defence.   \n  \nCapsuleer
    Grideris, a combat pilot with an anti-sansha stance, also expressed a belief that
    Sansha\u2019s Nation is focusing its attacks on trade routes. \u201CI believe
    they are doing this to try and break our ability to fight them. If Sansha\u2019s
    Nation were able to effectively cut these trade hubs from the rest of New Eden,
    it would cripple us.\u201D   \n  \nCapsuleer Hector von Hammerstorm, a self-declared
    Nation sympathizer, expressed a different view to Ace Echo and Grideris. \u201CI
    don't think it's a full-out attack; rather, they are attacking those gates to
    remind capsuleers \u2018We know your trades routes, and we can do something about
    it, if we wish.'\u201D   \n  \nVaerah Vahrokha, a trade specalist, provided an
    analysis of the actions of Sansha\u2019s Nation from an economic perspective.
    \u201CSansha's Nation attacks on trade routes are an attempt at cornering the
    markets and thus the progress of the affected regions. Whether this is just to
    disrupt and defeat defences or to convince the populations to accept Sansha's
    one-way deal is not known.\u201D   \n  \nVaerah offered advice for those caught
    up in Sansha's Nation attacks on trade hubs and shipping lanes. \u201CCapsuleers
    may rake benefits from the situation. They may join the defendants as well-paid
    soldiers or may form a network of smuggling agile and fleet-defended ships to
    breach Sansha's Nation blockades and be rewarded by the local populations.\u201D
    \n\n### GalNet References\n\n[Sansha Victory in Kador Prime](http://www.eveonline.com/news.asp?a=single&nid=4676&tid=7)
    \  \n[Sansha's Nation Attempts Jita Blockade](http://www.eveonline.com/news.asp?a=single&nid=4675&tid=7)
    \  \n[Capsuleers Successfully Drive Away Sansha's Nation Forces in Altrinur](http://www.eveonline.com/news.asp?a=single&nid=4673&tid=7)\n\n*
    * *\n\nAre you affected by the events in this article? Do you have information
    regarding another event in New Eden? If so, please [contact us](http://www.eveonline.com/news.asp?a=submitrp)
    with any information that you may have.  \n  \nWant to become a news correspondent
    with IC? We are [recruiting](http://www.eveonline.com/isd.asp)."
  id: 23VMpulsuT6FjLN8q3mZ9S
  layout: default
description: "New Caldari, The Forge \u2013 Sansha\u2019s Nation forces have been
  assaulting trade routes throughout New Eden, disrupting both market hubs hubs and
  popular shipping routes. Over the past two weeks, Sansha\u2019s Nation forces have
  attacked multiple solar systems including Kador Prime, New Caldari and Altrinur.
  It is their newfound interest in trade routes, however, that is causing concern
  among capsuleers. Capsuleer Ace Echo, who was present during the New Caldari attack,
  said \u201CThis recent rash of attacks seems to [...]"
heroImage: null
id: 5Wga8WO3wbOEp6mKbNTGHV
image: null
listingImage: null
parent: null
publicationDate: '2011-08-11T20:35:33+00:00'
slug: sanshas-nation-attacks-trade-routes
sortOrder: 0
title: "Sansha\u2019s Nation Attacks Trade Routes"
topics: []
updatedAt: '2021-06-11T20:22:58.282000+00:00'
