blank_issues_enabled: false
contact_links:
- name: ISD New Eden Correspondents
  url: https://volunteers.eveonline.com/
  about: Want to help improve EVE's lore, join the ISD New Eden Correspondents!
